<template>
  <div>
    <DemoHeader></DemoHeader>
    <router-view/>
	<div class="title">
		<img class="icon" src="../../assets/logo.png">
		<div>Call For Papers</div>
	</div>
	<div class="content">
		<section class="section">
            <a id="main-content" tabindex="-1"></a>
              <div class="region region-content">
    <div id="block-bartik-page-title" class="block block-core block-page-title-block">
  
  </div>
<div id="block-bartik-content" class="block block-system block-system-main-block">
  
    
      <div class="content">
      
<article data-history-node-id="1" role="article" typeof="schema:WebPage" class="node node--type-page node--view-mode-full clearfix">
  <header>
    
            <span property="schema:name" content="Call    for   Papers" class="rdf-meta hidden"></span>

      </header>
  <div class="node__content clearfix">
    
            <div property="schema:text" class="clearfix text-formatted field field--name-body field--type-text-with-summary field--label-hidden field__item"><p style="text-align:left; text-indent:0px; -webkit-text-stroke-width:0px" align="left"><span style="font-size:10.5pt"><span style="font-family:DengXian"><span style="caret-color:#000000"><span style="color:#000000"><span style="font-style:normal"><span style="font-variant-caps:normal"><span style="font-weight:normal"><span style="letter-spacing:normal"><span style="orphans:auto"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:auto"><span style="word-spacing:0px"><span style="-webkit-text-size-adjust:auto"><span style="text-decoration:none"><b><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif"><span style="color:black">The Asia Pacific Web (APWeb) and Web-Age Information Management (WAIM) Joint International Conference on Web and Big Data (APWeb-WAIM)</span></span></span></b><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif"><span style="color:black">&nbsp;is aiming at attracting professionals of different communities related to Web and Big Data who have common interests in interdisciplinary research to share and exchange ideas, experience and the underlying techniques and applications, including Web technologies, database systems, information management, software engineering and big data. Starting in 2017, the two conference committees have agreed to launch a joint conference. With the increased focus on Big Data, the new joint conference is expected to attract more professionals from different industrial and academic communities, not only from the Asia Pacific countries but also from other continents.</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="text-align:left; text-indent:0px; -webkit-text-stroke-width:0px" align="left"><span style="font-size:10.5pt"><span style="font-family:DengXian"><span style="caret-color:#000000"><span style="color:#000000"><span style="font-style:normal"><span style="font-variant-caps:normal"><span style="font-weight:normal"><span style="letter-spacing:normal"><span style="orphans:auto"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:auto"><span style="word-spacing:0px"><span style="-webkit-text-size-adjust:auto"><span style="text-decoration:none"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif"><span style="color:black">The 4th APWeb-WAIM joint international conference on Web and Big Data 2020 will take place in Tianjin, China. Tianjin is one of China's four municipalities under the direct administration of central government. It is an international port city and the largest seaside city in the North of China. It is our sincere hope that you will make best of your time here to visit more places and enjoy more scenery and we believe you will harvest a lot.</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="text-align:left; text-indent:0px; -webkit-text-stroke-width:0px" align="left"><span style="font-size:10.5pt"><span style="font-family:DengXian"><span style="caret-color:#000000"><span style="color:#000000"><span style="font-style:normal"><span style="font-variant-caps:normal"><span style="font-weight:normal"><span style="letter-spacing:normal"><span style="orphans:auto"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:auto"><span style="word-spacing:0px"><span style="-webkit-text-size-adjust:auto"><span style="text-decoration:none"><b><span style="font-size:16pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif"><span style="color:black">Important Dates</span></span></span></b></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<ul><li style="text-align:left; font-size:10.5pt; font-family:DengXian; color:black; margin-bottom:0px"><b><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Abstract submission:&nbsp;February 9, 2020&nbsp;</span></span></b></li>

	<li style="text-align:left"><span style="font-size:10.5pt"><span style="font-family:DengXian"><span style="caret-color:#000000"><span style="color:#000000"><span style="font-style:normal"><span style="font-variant-caps:normal"><span style="font-weight:normal"><span style="letter-spacing:normal"><span style="orphans:auto"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:auto"><span style="word-spacing:0px"><span style="-webkit-text-size-adjust:auto"><span style="text-decoration:none"><b><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif"><span style="color:black">Acceptance Notification:&nbsp;April 23, 2020</span></span></span></b></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></li>
	<li style="text-align:left"><b><span style="font-size:12.0pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Camera Ready: May 8, 2020 </span></span></b></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Conference Date: </span></span></span></span></span></span><b><span style="font-size:12.0pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">August 12-14, 2020</span></span></b><b><span style="font-size:12.0pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"></span></span></b></li>

</ul><p style="text-align:left; text-indent:0px; -webkit-text-stroke-width:0px" align="left"><span style="font-size:10.5pt"><span style="font-family:DengXian"><span style="caret-color:#000000"><span style="color:#000000"><span style="font-style:normal"><span style="font-variant-caps:normal"><span style="font-weight:normal"><span style="letter-spacing:normal"><span style="orphans:auto"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:auto"><span style="word-spacing:0px"><span style="-webkit-text-size-adjust:auto"><span style="text-decoration:none"><b><span style="font-size:16pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif"><span style="color:black">Topics of Interest, but not limited to</span></span></span></b></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<ul><li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Advanced database and Web applications</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Big data analytics</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Big data management</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Block chain models and applications</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Caching and replication</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Cloud computing</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Content management</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Crowdsourcing</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Data and information quality</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Data management for mobile and pervasive computing</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Data management on new hardware</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Data mining</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Data provenance and workflow</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Data warehousing and OLAP</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Deep Web</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Digital libraries</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Entity resolution and entity linking</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Graph data management, RDF, social networks</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Information extraction</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Information integration and heterogeneous systems</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Information retrieval</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Knowledge extraction and management</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Multimedia information systems</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Machine Learning</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Parallel and distributed data management</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Query processing and optimization</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Recommender systems</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Security, privacy, and trust</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Semantic Web and ontology</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Sensor networks</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Service-oriented computing</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Social media</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Spatial and temporal databases</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Storage and access methods</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Streams, complex event processing</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Text database, keyword search</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Uncertain data</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Web advertising and community analysis</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Web information quality and fusion</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Web search and meta-search</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">Web service management</span></span></span></span></span></span></li>
	<li style="text-align:left"><span style="font-size:10.5pt"><span style="color:black"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif">XML and semi-structured data</span></span></span></span></span></span></li>
</ul><p style="text-align:left; text-indent:0px; -webkit-text-stroke-width:0px" align="left"><span style="font-size:10.5pt"><span style="font-family:DengXian"><span style="caret-color:#000000"><span style="color:#000000"><span style="font-style:normal"><span style="font-variant-caps:normal"><span style="font-weight:normal"><span style="letter-spacing:normal"><span style="orphans:auto"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:auto"><span style="word-spacing:0px"><span style="-webkit-text-size-adjust:auto"><span style="text-decoration:none"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif"><span style="color:black">Authors should submit papers reporting original work that are currently not under review or published elsewhere. Accepted papers will be published in the conference proceedings, which will be published as a volume of&nbsp;<b>Springer's Lecture Notes in Computer Science (LNCS)</b>series.&nbsp;</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="text-align:left; text-indent:0px; -webkit-text-stroke-width:0px" align="left"><span style="font-size:10.5pt"><span style="font-family:DengXian"><span style="caret-color:#000000"><span style="color:#000000"><span style="font-style:normal"><span style="font-variant-caps:normal"><span style="font-weight:normal"><span style="letter-spacing:normal"><span style="orphans:auto"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:auto"><span style="word-spacing:0px"><span style="-webkit-text-size-adjust:auto"><span style="text-decoration:none"><b><span style="font-size:16pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif"><span style="color:black">Paper Submission</span></span></span></b></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="text-align:left; text-indent:0px; -webkit-text-stroke-width:0px" align="left"><span style="font-size:10.5pt"><span style="font-family:DengXian"><span style="caret-color:#000000"><span style="color:#000000"><span style="font-style:normal"><span style="font-variant-caps:normal"><span style="font-weight:normal"><span style="letter-spacing:normal"><span style="orphans:auto"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:auto"><span style="word-spacing:0px"><span style="-webkit-text-size-adjust:auto"><span style="text-decoration:none"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif"><span style="color:black">All papers should be submitted through the Conference Management Tool at:&nbsp;<a href="https://cmt3.research.microsoft.com/apwebwaim2020"><span style="color:blue">https://cmt3.research.microsoft.com/apwebwaim2020</span></a>&nbsp;</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="text-align:left; text-indent:0px; -webkit-text-stroke-width:0px; margin-bottom:19px" align="left"><span style="font-size:10.5pt"><span style="font-family:DengXian"><span style="caret-color:#000000"><span style="color:#000000"><span style="font-style:normal"><span style="font-variant-caps:normal"><span style="font-weight:normal"><span style="letter-spacing:normal"><span style="orphans:auto"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:auto"><span style="word-spacing:0px"><span style="-webkit-text-size-adjust:auto"><span style="text-decoration:none"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:Times"><span style="color:black">Submissions must be written in English and not exceed 15 pages in LNCS format, including references. All submissions must be in PDF format. Authors should avoid the use of non-English fonts to avoid problems with printing and viewing the submissions.</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="text-align:left; text-indent:0px; -webkit-text-stroke-width:0px; margin-bottom:19px" align="left"><span style="font-size:10.5pt"><span style="font-family:DengXian"><span style="caret-color:#000000"><span style="color:#000000"><span style="font-style:normal"><span style="font-variant-caps:normal"><span style="font-weight:normal"><span style="letter-spacing:normal"><span style="orphans:auto"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:auto"><span style="word-spacing:0px"><span style="-webkit-text-size-adjust:auto"><span style="text-decoration:none"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:Times"><span style="color:black">Submitted papers will undergo a&nbsp;</span></span></span><strong><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:Times"><span style="color:red">double-blind reviewing process</span></span></span></strong><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:Times"><span style="color:black">. The PC members and referees who review the paper will not know the identity of the authors. To ensure anonymity of authorship, authors must prepare their manuscript as follows:</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<ul><li align="left" style="text-align:left"><span style="font-size:10.5pt"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:Times"><span style="color:black">Authors' names and affiliations must not appear on the title page or elsewhere in the paper.</span></span></span></span></span></span></li>
	<li align="left" style="text-align:left"><span style="font-size:10.5pt"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:Times"><span style="color:black">Funding sources must not be acknowledged on the title page or elsewhere in the paper.</span></span></span></span></span></span></li>
	<li align="left" style="text-align:left"><span style="font-size:10.5pt"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:Times"><span style="color:black">Research group members, or other colleagues or collaborators, must not be acknowledged anywhere in the paper.</span></span></span></span></span></span></li>
	<li align="left" style="text-align:left"><span style="font-size:10.5pt"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:Times"><span style="color:black">The paper's file name must not identify the authors of the paper. It is strongly suggested that the submitted file be named with the assigned submission number. For example, if your assigned paper number is 382, then name your submission file 382.pdf.</span></span></span></span></span></span></li>
	<li align="left" style="text-align:left"><span style="font-size:10.5pt"><span style="tab-stops:list 36.0pt"><span style="font-family:DengXian"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:Times"><span style="color:black">Source file naming must also be done with care, to avoid identifying the authors' name in the paper's associated metadata. For example, if your name is Jane Smith and you submit a PDF file generated from a .dvi file called Jane-Smith.dvi, your authorship could be inferred by looking into the PDF file.</span></span></span></span></span></span></li>
</ul><p style="text-align:left; text-indent:0px; -webkit-text-stroke-width:0px; margin-bottom:19px" align="left"><span style="font-size:10.5pt"><span style="font-family:DengXian"><span style="caret-color:#000000"><span style="color:#000000"><span style="font-style:normal"><span style="font-variant-caps:normal"><span style="font-weight:normal"><span style="letter-spacing:normal"><span style="orphans:auto"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:auto"><span style="word-spacing:0px"><span style="-webkit-text-size-adjust:auto"><span style="text-decoration:none"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:Times"><span style="color:black">It is the responsibility of authors to do their very best to preserve anonymity. Papers that do not follow the above GUILDLINES, or otherwise potentially reveal the identity of the authors, are subject to desk rejection.</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="text-align:left; text-indent:0px; -webkit-text-stroke-width:0px" align="left"><span style="font-size:10.5pt"><span style="font-family:DengXian"><span style="caret-color:#000000"><span style="color:#000000"><span style="font-style:normal"><span style="font-variant-caps:normal"><span style="font-weight:normal"><span style="letter-spacing:normal"><span style="orphans:auto"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:auto"><span style="word-spacing:0px"><span style="-webkit-text-size-adjust:auto"><span style="text-decoration:none"><b><span style="font-size:16pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif"><span style="color:black">Recommendation to Journal</span></span></span></b></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="text-align:left; text-indent:0px; -webkit-text-stroke-width:0px" align="left"><span style="font-size:10.5pt"><span style="font-family:DengXian"><span style="caret-color:#000000"><span style="color:#000000"><span style="font-style:normal"><span style="font-variant-caps:normal"><span style="font-weight:normal"><span style="letter-spacing:normal"><span style="orphans:auto"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:auto"><span style="word-spacing:0px"><span style="-webkit-text-size-adjust:auto"><span style="text-decoration:none"><span style="font-size:12pt" xml:lang="EN-US" lang="EN-US"><span style="font-family:&quot;Times New Roman&quot;, serif"><span style="color:black">A number of best papers accepted at APWeb-WAIM 2021 will be recommended to a set of SCI indexed journals, including&nbsp;<b>World Wide Web Journal (IF 1.770, JCR Q2), Big Data Research (IF2.952, JCR Q2),&nbsp;</b>and journal&nbsp;<b>Data Science Engineering</b>, for fast-track publication in special issues in these journals.</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>
</div>
      
  </div>
</article>

    </div>
  </div>

  </div>

          </section>
	</div>
    <DemoFooter></DemoFooter>
  </div>
</template>

<script>
import DemoHeader from "@/components/DemoHeader";
import DemoFooter from "@/components/DemoFooter";
export default {
  name: "Tutorial",
  components: {DemoFooter, DemoHeader}
}
</script>

<style scoped>

.content{
	width: 1200px;
	margin:0 auto;
	text-align: left;
}
.icon{
	width: 100px;
}
.pad-33-em {
	padding: .33em 0;
	font-size: 18px;
	font-weight: bold;
}
.title {
	font-size:26px;
	color:#2db2ffff;
}
</style>